### ISSUE TITLE
What's the predicted start date for the MoCCA Specialization?

### ISSUE THREAD

**Issue by tiagomestreteixeira** [douglascraigschmidt/Android-App-Development#2]
@douglascraigschmidt 
@MonteCreasor 

Thanks in advance,
You've built a very enjoyable Android Specialization. Thank you for that!

**Comment by douglascraigschmidt** [comment]
Hi Tiago, there is currently no predicted start date for the MoCCA specialization.  In the meantime, I recommend you check out 

https://www.safaribooksonline.com/live-training/courses/java-8-concurrency/0636920093763

(which runs at the end of August for two days) and

http://www.dre.vanderbilt.edu/~schmidt/cs891/

(which starts towards the end of August for 15 weeks).

Doug
