### ISSUE TITLE
jdk 7 is removed from oracle , its only open for its users please help me

### ISSUE THREAD

**Issue by Aarush786** [douglascraigschmidt/Android-App-Development#4]

**Comment by douglascraigschmidt** [comment]
Please see https://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html for instructions on how to download Java 7.  Alternatively, just upgrade to Java 8 (or beyond) and things should work fine.

**Comment by Aarush786** [comment]
my first assignment of java for android is not working in java 8

**Comment by douglascraigschmidt** [comment]
Java 8 and Java 7 should behave identically for the "Java for Android" assignments, so there's probably a problem with your code.  However, please see the URL above for instructions on how to download/install Java 7.

**Comment by Aarush786** [comment]
when i installed the code which was given in your assignment it started but was showing no tool chains found and gradle build not working

**Comment by douglascraigschmidt** [comment]
This has nothing to do with Java 8 vs. Java 7 - you simply haven't configured Android Studio properly..  Please google a bit to find out what's causing the error message and how to fix it.

**Comment by Aarush786** [comment]
this is the assignment of your 1st mooc of java for android , i searched all the google but nothing is working , i think the file of your assignment is old ,the web pages which are shown by build sync  are not available , when i clicked them  error 404 is coming, hope you will understand and help me.
Thanks and Regards

**Comment by Aarush786** [comment]
the location of your gradle files are not available

**Comment by MonteCreasor** [comment]
You need to download the project skeleton again because you have changed the build.gradle to use an invalid plugin. Unless you really know what you are doing, my advice is not not directly edit the build.gradle file. Instead, always let Android Studio update the Android plugin in build.gradle file for you when you first open the skeleton project. Always select yes when Android Studio asks if you want it to update the Android gradle plugin (or the gradle wrapper).

**Comment by Aarush786** [comment]
![screenshot 16](https://user-images.githubusercontent.com/44872732/48312763-a6913c00-e5d9-11e8-9ff9-69301ff9a30d.png)

**Comment by Aarush786** [comment]
this is coming in freshly opened project,my android studio is also up to date.

**Comment by douglascraigschmidt** [comment]
That error message indicates that your Android Studio SDK isn't installed properly. Make sure you've installed the NDK toolchain for ABI with prefix mipsel-linux-android.
